
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ResearchJob` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ResearchJob
 * 
 */
export type ResearchJobModel = runtime.Types.Result.DefaultSelection<Prisma.$ResearchJobPayload>

export type AggregateResearchJob = {
  _count: ResearchJobCountAggregateOutputType | null
  _avg: ResearchJobAvgAggregateOutputType | null
  _sum: ResearchJobSumAggregateOutputType | null
  _min: ResearchJobMinAggregateOutputType | null
  _max: ResearchJobMaxAggregateOutputType | null
}

export type ResearchJobAvgAggregateOutputType = {
  progress: number | null
  articlesFound: number | null
  articlesProcessed: number | null
}

export type ResearchJobSumAggregateOutputType = {
  progress: number | null
  articlesFound: number | null
  articlesProcessed: number | null
}

export type ResearchJobMinAggregateOutputType = {
  id: string | null
  topic: string | null
  mode: string | null
  status: string | null
  progress: number | null
  error: string | null
  queries: string | null
  articlesFound: number | null
  articlesProcessed: number | null
  startTime: Date | null
  endTime: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  includedIds: string | null
  excludedIds: string | null
  exclusionReasons: string | null
  reviewText: string | null
  graphId: string | null
}

export type ResearchJobMaxAggregateOutputType = {
  id: string | null
  topic: string | null
  mode: string | null
  status: string | null
  progress: number | null
  error: string | null
  queries: string | null
  articlesFound: number | null
  articlesProcessed: number | null
  startTime: Date | null
  endTime: Date | null
  createdAt: Date | null
  updatedAt: Date | null
  includedIds: string | null
  excludedIds: string | null
  exclusionReasons: string | null
  reviewText: string | null
  graphId: string | null
}

export type ResearchJobCountAggregateOutputType = {
  id: number
  topic: number
  mode: number
  status: number
  progress: number
  error: number
  queries: number
  articlesFound: number
  articlesProcessed: number
  startTime: number
  endTime: number
  createdAt: number
  updatedAt: number
  includedIds: number
  excludedIds: number
  exclusionReasons: number
  reviewText: number
  graphId: number
  _all: number
}


export type ResearchJobAvgAggregateInputType = {
  progress?: true
  articlesFound?: true
  articlesProcessed?: true
}

export type ResearchJobSumAggregateInputType = {
  progress?: true
  articlesFound?: true
  articlesProcessed?: true
}

export type ResearchJobMinAggregateInputType = {
  id?: true
  topic?: true
  mode?: true
  status?: true
  progress?: true
  error?: true
  queries?: true
  articlesFound?: true
  articlesProcessed?: true
  startTime?: true
  endTime?: true
  createdAt?: true
  updatedAt?: true
  includedIds?: true
  excludedIds?: true
  exclusionReasons?: true
  reviewText?: true
  graphId?: true
}

export type ResearchJobMaxAggregateInputType = {
  id?: true
  topic?: true
  mode?: true
  status?: true
  progress?: true
  error?: true
  queries?: true
  articlesFound?: true
  articlesProcessed?: true
  startTime?: true
  endTime?: true
  createdAt?: true
  updatedAt?: true
  includedIds?: true
  excludedIds?: true
  exclusionReasons?: true
  reviewText?: true
  graphId?: true
}

export type ResearchJobCountAggregateInputType = {
  id?: true
  topic?: true
  mode?: true
  status?: true
  progress?: true
  error?: true
  queries?: true
  articlesFound?: true
  articlesProcessed?: true
  startTime?: true
  endTime?: true
  createdAt?: true
  updatedAt?: true
  includedIds?: true
  excludedIds?: true
  exclusionReasons?: true
  reviewText?: true
  graphId?: true
  _all?: true
}

export type ResearchJobAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ResearchJob to aggregate.
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ResearchJobs to fetch.
   */
  orderBy?: Prisma.ResearchJobOrderByWithRelationInput | Prisma.ResearchJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ResearchJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ResearchJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ResearchJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ResearchJobs
  **/
  _count?: true | ResearchJobCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ResearchJobAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ResearchJobSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ResearchJobMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ResearchJobMaxAggregateInputType
}

export type GetResearchJobAggregateType<T extends ResearchJobAggregateArgs> = {
      [P in keyof T & keyof AggregateResearchJob]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateResearchJob[P]>
    : Prisma.GetScalarType<T[P], AggregateResearchJob[P]>
}




export type ResearchJobGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ResearchJobWhereInput
  orderBy?: Prisma.ResearchJobOrderByWithAggregationInput | Prisma.ResearchJobOrderByWithAggregationInput[]
  by: Prisma.ResearchJobScalarFieldEnum[] | Prisma.ResearchJobScalarFieldEnum
  having?: Prisma.ResearchJobScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ResearchJobCountAggregateInputType | true
  _avg?: ResearchJobAvgAggregateInputType
  _sum?: ResearchJobSumAggregateInputType
  _min?: ResearchJobMinAggregateInputType
  _max?: ResearchJobMaxAggregateInputType
}

export type ResearchJobGroupByOutputType = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime: Date | null
  endTime: Date | null
  createdAt: Date
  updatedAt: Date
  includedIds: string | null
  excludedIds: string | null
  exclusionReasons: string | null
  reviewText: string | null
  graphId: string | null
  _count: ResearchJobCountAggregateOutputType | null
  _avg: ResearchJobAvgAggregateOutputType | null
  _sum: ResearchJobSumAggregateOutputType | null
  _min: ResearchJobMinAggregateOutputType | null
  _max: ResearchJobMaxAggregateOutputType | null
}

type GetResearchJobGroupByPayload<T extends ResearchJobGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ResearchJobGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ResearchJobGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ResearchJobGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ResearchJobGroupByOutputType[P]>
      }
    >
  >



export type ResearchJobWhereInput = {
  AND?: Prisma.ResearchJobWhereInput | Prisma.ResearchJobWhereInput[]
  OR?: Prisma.ResearchJobWhereInput[]
  NOT?: Prisma.ResearchJobWhereInput | Prisma.ResearchJobWhereInput[]
  id?: Prisma.StringFilter<"ResearchJob"> | string
  topic?: Prisma.StringFilter<"ResearchJob"> | string
  mode?: Prisma.StringFilter<"ResearchJob"> | string
  status?: Prisma.StringFilter<"ResearchJob"> | string
  progress?: Prisma.IntFilter<"ResearchJob"> | number
  error?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  queries?: Prisma.StringFilter<"ResearchJob"> | string
  articlesFound?: Prisma.IntFilter<"ResearchJob"> | number
  articlesProcessed?: Prisma.IntFilter<"ResearchJob"> | number
  startTime?: Prisma.DateTimeNullableFilter<"ResearchJob"> | Date | string | null
  endTime?: Prisma.DateTimeNullableFilter<"ResearchJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ResearchJob"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ResearchJob"> | Date | string
  includedIds?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  excludedIds?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  exclusionReasons?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  reviewText?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  graphId?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  articles?: Prisma.ArticleListRelationFilter
  graph?: Prisma.XOR<Prisma.GraphNullableScalarRelationFilter, Prisma.GraphWhereInput> | null
}

export type ResearchJobOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  queries?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
  startTime?: Prisma.SortOrderInput | Prisma.SortOrder
  endTime?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  includedIds?: Prisma.SortOrderInput | Prisma.SortOrder
  excludedIds?: Prisma.SortOrderInput | Prisma.SortOrder
  exclusionReasons?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewText?: Prisma.SortOrderInput | Prisma.SortOrder
  graphId?: Prisma.SortOrderInput | Prisma.SortOrder
  articles?: Prisma.ArticleOrderByRelationAggregateInput
  graph?: Prisma.GraphOrderByWithRelationInput
}

export type ResearchJobWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ResearchJobWhereInput | Prisma.ResearchJobWhereInput[]
  OR?: Prisma.ResearchJobWhereInput[]
  NOT?: Prisma.ResearchJobWhereInput | Prisma.ResearchJobWhereInput[]
  topic?: Prisma.StringFilter<"ResearchJob"> | string
  mode?: Prisma.StringFilter<"ResearchJob"> | string
  status?: Prisma.StringFilter<"ResearchJob"> | string
  progress?: Prisma.IntFilter<"ResearchJob"> | number
  error?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  queries?: Prisma.StringFilter<"ResearchJob"> | string
  articlesFound?: Prisma.IntFilter<"ResearchJob"> | number
  articlesProcessed?: Prisma.IntFilter<"ResearchJob"> | number
  startTime?: Prisma.DateTimeNullableFilter<"ResearchJob"> | Date | string | null
  endTime?: Prisma.DateTimeNullableFilter<"ResearchJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ResearchJob"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ResearchJob"> | Date | string
  includedIds?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  excludedIds?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  exclusionReasons?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  reviewText?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  graphId?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  articles?: Prisma.ArticleListRelationFilter
  graph?: Prisma.XOR<Prisma.GraphNullableScalarRelationFilter, Prisma.GraphWhereInput> | null
}, "id">

export type ResearchJobOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  queries?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
  startTime?: Prisma.SortOrderInput | Prisma.SortOrder
  endTime?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  includedIds?: Prisma.SortOrderInput | Prisma.SortOrder
  excludedIds?: Prisma.SortOrderInput | Prisma.SortOrder
  exclusionReasons?: Prisma.SortOrderInput | Prisma.SortOrder
  reviewText?: Prisma.SortOrderInput | Prisma.SortOrder
  graphId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ResearchJobCountOrderByAggregateInput
  _avg?: Prisma.ResearchJobAvgOrderByAggregateInput
  _max?: Prisma.ResearchJobMaxOrderByAggregateInput
  _min?: Prisma.ResearchJobMinOrderByAggregateInput
  _sum?: Prisma.ResearchJobSumOrderByAggregateInput
}

export type ResearchJobScalarWhereWithAggregatesInput = {
  AND?: Prisma.ResearchJobScalarWhereWithAggregatesInput | Prisma.ResearchJobScalarWhereWithAggregatesInput[]
  OR?: Prisma.ResearchJobScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ResearchJobScalarWhereWithAggregatesInput | Prisma.ResearchJobScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ResearchJob"> | string
  topic?: Prisma.StringWithAggregatesFilter<"ResearchJob"> | string
  mode?: Prisma.StringWithAggregatesFilter<"ResearchJob"> | string
  status?: Prisma.StringWithAggregatesFilter<"ResearchJob"> | string
  progress?: Prisma.IntWithAggregatesFilter<"ResearchJob"> | number
  error?: Prisma.StringNullableWithAggregatesFilter<"ResearchJob"> | string | null
  queries?: Prisma.StringWithAggregatesFilter<"ResearchJob"> | string
  articlesFound?: Prisma.IntWithAggregatesFilter<"ResearchJob"> | number
  articlesProcessed?: Prisma.IntWithAggregatesFilter<"ResearchJob"> | number
  startTime?: Prisma.DateTimeNullableWithAggregatesFilter<"ResearchJob"> | Date | string | null
  endTime?: Prisma.DateTimeNullableWithAggregatesFilter<"ResearchJob"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ResearchJob"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ResearchJob"> | Date | string
  includedIds?: Prisma.StringNullableWithAggregatesFilter<"ResearchJob"> | string | null
  excludedIds?: Prisma.StringNullableWithAggregatesFilter<"ResearchJob"> | string | null
  exclusionReasons?: Prisma.StringNullableWithAggregatesFilter<"ResearchJob"> | string | null
  reviewText?: Prisma.StringNullableWithAggregatesFilter<"ResearchJob"> | string | null
  graphId?: Prisma.StringNullableWithAggregatesFilter<"ResearchJob"> | string | null
}

export type ResearchJobCreateInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  articles?: Prisma.ArticleCreateNestedManyWithoutJobInput
  graph?: Prisma.GraphCreateNestedOneWithoutJobsInput
}

export type ResearchJobUncheckedCreateInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  graphId?: string | null
  articles?: Prisma.ArticleUncheckedCreateNestedManyWithoutJobInput
}

export type ResearchJobUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articles?: Prisma.ArticleUpdateManyWithoutJobNestedInput
  graph?: Prisma.GraphUpdateOneWithoutJobsNestedInput
}

export type ResearchJobUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  graphId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articles?: Prisma.ArticleUncheckedUpdateManyWithoutJobNestedInput
}

export type ResearchJobCreateManyInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  graphId?: string | null
}

export type ResearchJobUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ResearchJobUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  graphId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ResearchJobCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  error?: Prisma.SortOrder
  queries?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  includedIds?: Prisma.SortOrder
  excludedIds?: Prisma.SortOrder
  exclusionReasons?: Prisma.SortOrder
  reviewText?: Prisma.SortOrder
  graphId?: Prisma.SortOrder
}

export type ResearchJobAvgOrderByAggregateInput = {
  progress?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
}

export type ResearchJobMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  error?: Prisma.SortOrder
  queries?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  includedIds?: Prisma.SortOrder
  excludedIds?: Prisma.SortOrder
  exclusionReasons?: Prisma.SortOrder
  reviewText?: Prisma.SortOrder
  graphId?: Prisma.SortOrder
}

export type ResearchJobMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  topic?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  error?: Prisma.SortOrder
  queries?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  includedIds?: Prisma.SortOrder
  excludedIds?: Prisma.SortOrder
  exclusionReasons?: Prisma.SortOrder
  reviewText?: Prisma.SortOrder
  graphId?: Prisma.SortOrder
}

export type ResearchJobSumOrderByAggregateInput = {
  progress?: Prisma.SortOrder
  articlesFound?: Prisma.SortOrder
  articlesProcessed?: Prisma.SortOrder
}

export type ResearchJobScalarRelationFilter = {
  is?: Prisma.ResearchJobWhereInput
  isNot?: Prisma.ResearchJobWhereInput
}

export type ResearchJobListRelationFilter = {
  every?: Prisma.ResearchJobWhereInput
  some?: Prisma.ResearchJobWhereInput
  none?: Prisma.ResearchJobWhereInput
}

export type ResearchJobOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type ResearchJobCreateNestedOneWithoutArticlesInput = {
  create?: Prisma.XOR<Prisma.ResearchJobCreateWithoutArticlesInput, Prisma.ResearchJobUncheckedCreateWithoutArticlesInput>
  connectOrCreate?: Prisma.ResearchJobCreateOrConnectWithoutArticlesInput
  connect?: Prisma.ResearchJobWhereUniqueInput
}

export type ResearchJobUpdateOneRequiredWithoutArticlesNestedInput = {
  create?: Prisma.XOR<Prisma.ResearchJobCreateWithoutArticlesInput, Prisma.ResearchJobUncheckedCreateWithoutArticlesInput>
  connectOrCreate?: Prisma.ResearchJobCreateOrConnectWithoutArticlesInput
  upsert?: Prisma.ResearchJobUpsertWithoutArticlesInput
  connect?: Prisma.ResearchJobWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ResearchJobUpdateToOneWithWhereWithoutArticlesInput, Prisma.ResearchJobUpdateWithoutArticlesInput>, Prisma.ResearchJobUncheckedUpdateWithoutArticlesInput>
}

export type ResearchJobCreateNestedManyWithoutGraphInput = {
  create?: Prisma.XOR<Prisma.ResearchJobCreateWithoutGraphInput, Prisma.ResearchJobUncheckedCreateWithoutGraphInput> | Prisma.ResearchJobCreateWithoutGraphInput[] | Prisma.ResearchJobUncheckedCreateWithoutGraphInput[]
  connectOrCreate?: Prisma.ResearchJobCreateOrConnectWithoutGraphInput | Prisma.ResearchJobCreateOrConnectWithoutGraphInput[]
  createMany?: Prisma.ResearchJobCreateManyGraphInputEnvelope
  connect?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
}

export type ResearchJobUncheckedCreateNestedManyWithoutGraphInput = {
  create?: Prisma.XOR<Prisma.ResearchJobCreateWithoutGraphInput, Prisma.ResearchJobUncheckedCreateWithoutGraphInput> | Prisma.ResearchJobCreateWithoutGraphInput[] | Prisma.ResearchJobUncheckedCreateWithoutGraphInput[]
  connectOrCreate?: Prisma.ResearchJobCreateOrConnectWithoutGraphInput | Prisma.ResearchJobCreateOrConnectWithoutGraphInput[]
  createMany?: Prisma.ResearchJobCreateManyGraphInputEnvelope
  connect?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
}

export type ResearchJobUpdateManyWithoutGraphNestedInput = {
  create?: Prisma.XOR<Prisma.ResearchJobCreateWithoutGraphInput, Prisma.ResearchJobUncheckedCreateWithoutGraphInput> | Prisma.ResearchJobCreateWithoutGraphInput[] | Prisma.ResearchJobUncheckedCreateWithoutGraphInput[]
  connectOrCreate?: Prisma.ResearchJobCreateOrConnectWithoutGraphInput | Prisma.ResearchJobCreateOrConnectWithoutGraphInput[]
  upsert?: Prisma.ResearchJobUpsertWithWhereUniqueWithoutGraphInput | Prisma.ResearchJobUpsertWithWhereUniqueWithoutGraphInput[]
  createMany?: Prisma.ResearchJobCreateManyGraphInputEnvelope
  set?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  disconnect?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  delete?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  connect?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  update?: Prisma.ResearchJobUpdateWithWhereUniqueWithoutGraphInput | Prisma.ResearchJobUpdateWithWhereUniqueWithoutGraphInput[]
  updateMany?: Prisma.ResearchJobUpdateManyWithWhereWithoutGraphInput | Prisma.ResearchJobUpdateManyWithWhereWithoutGraphInput[]
  deleteMany?: Prisma.ResearchJobScalarWhereInput | Prisma.ResearchJobScalarWhereInput[]
}

export type ResearchJobUncheckedUpdateManyWithoutGraphNestedInput = {
  create?: Prisma.XOR<Prisma.ResearchJobCreateWithoutGraphInput, Prisma.ResearchJobUncheckedCreateWithoutGraphInput> | Prisma.ResearchJobCreateWithoutGraphInput[] | Prisma.ResearchJobUncheckedCreateWithoutGraphInput[]
  connectOrCreate?: Prisma.ResearchJobCreateOrConnectWithoutGraphInput | Prisma.ResearchJobCreateOrConnectWithoutGraphInput[]
  upsert?: Prisma.ResearchJobUpsertWithWhereUniqueWithoutGraphInput | Prisma.ResearchJobUpsertWithWhereUniqueWithoutGraphInput[]
  createMany?: Prisma.ResearchJobCreateManyGraphInputEnvelope
  set?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  disconnect?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  delete?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  connect?: Prisma.ResearchJobWhereUniqueInput | Prisma.ResearchJobWhereUniqueInput[]
  update?: Prisma.ResearchJobUpdateWithWhereUniqueWithoutGraphInput | Prisma.ResearchJobUpdateWithWhereUniqueWithoutGraphInput[]
  updateMany?: Prisma.ResearchJobUpdateManyWithWhereWithoutGraphInput | Prisma.ResearchJobUpdateManyWithWhereWithoutGraphInput[]
  deleteMany?: Prisma.ResearchJobScalarWhereInput | Prisma.ResearchJobScalarWhereInput[]
}

export type ResearchJobCreateWithoutArticlesInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  graph?: Prisma.GraphCreateNestedOneWithoutJobsInput
}

export type ResearchJobUncheckedCreateWithoutArticlesInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  graphId?: string | null
}

export type ResearchJobCreateOrConnectWithoutArticlesInput = {
  where: Prisma.ResearchJobWhereUniqueInput
  create: Prisma.XOR<Prisma.ResearchJobCreateWithoutArticlesInput, Prisma.ResearchJobUncheckedCreateWithoutArticlesInput>
}

export type ResearchJobUpsertWithoutArticlesInput = {
  update: Prisma.XOR<Prisma.ResearchJobUpdateWithoutArticlesInput, Prisma.ResearchJobUncheckedUpdateWithoutArticlesInput>
  create: Prisma.XOR<Prisma.ResearchJobCreateWithoutArticlesInput, Prisma.ResearchJobUncheckedCreateWithoutArticlesInput>
  where?: Prisma.ResearchJobWhereInput
}

export type ResearchJobUpdateToOneWithWhereWithoutArticlesInput = {
  where?: Prisma.ResearchJobWhereInput
  data: Prisma.XOR<Prisma.ResearchJobUpdateWithoutArticlesInput, Prisma.ResearchJobUncheckedUpdateWithoutArticlesInput>
}

export type ResearchJobUpdateWithoutArticlesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  graph?: Prisma.GraphUpdateOneWithoutJobsNestedInput
}

export type ResearchJobUncheckedUpdateWithoutArticlesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  graphId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ResearchJobCreateWithoutGraphInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  articles?: Prisma.ArticleCreateNestedManyWithoutJobInput
}

export type ResearchJobUncheckedCreateWithoutGraphInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
  articles?: Prisma.ArticleUncheckedCreateNestedManyWithoutJobInput
}

export type ResearchJobCreateOrConnectWithoutGraphInput = {
  where: Prisma.ResearchJobWhereUniqueInput
  create: Prisma.XOR<Prisma.ResearchJobCreateWithoutGraphInput, Prisma.ResearchJobUncheckedCreateWithoutGraphInput>
}

export type ResearchJobCreateManyGraphInputEnvelope = {
  data: Prisma.ResearchJobCreateManyGraphInput | Prisma.ResearchJobCreateManyGraphInput[]
}

export type ResearchJobUpsertWithWhereUniqueWithoutGraphInput = {
  where: Prisma.ResearchJobWhereUniqueInput
  update: Prisma.XOR<Prisma.ResearchJobUpdateWithoutGraphInput, Prisma.ResearchJobUncheckedUpdateWithoutGraphInput>
  create: Prisma.XOR<Prisma.ResearchJobCreateWithoutGraphInput, Prisma.ResearchJobUncheckedCreateWithoutGraphInput>
}

export type ResearchJobUpdateWithWhereUniqueWithoutGraphInput = {
  where: Prisma.ResearchJobWhereUniqueInput
  data: Prisma.XOR<Prisma.ResearchJobUpdateWithoutGraphInput, Prisma.ResearchJobUncheckedUpdateWithoutGraphInput>
}

export type ResearchJobUpdateManyWithWhereWithoutGraphInput = {
  where: Prisma.ResearchJobScalarWhereInput
  data: Prisma.XOR<Prisma.ResearchJobUpdateManyMutationInput, Prisma.ResearchJobUncheckedUpdateManyWithoutGraphInput>
}

export type ResearchJobScalarWhereInput = {
  AND?: Prisma.ResearchJobScalarWhereInput | Prisma.ResearchJobScalarWhereInput[]
  OR?: Prisma.ResearchJobScalarWhereInput[]
  NOT?: Prisma.ResearchJobScalarWhereInput | Prisma.ResearchJobScalarWhereInput[]
  id?: Prisma.StringFilter<"ResearchJob"> | string
  topic?: Prisma.StringFilter<"ResearchJob"> | string
  mode?: Prisma.StringFilter<"ResearchJob"> | string
  status?: Prisma.StringFilter<"ResearchJob"> | string
  progress?: Prisma.IntFilter<"ResearchJob"> | number
  error?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  queries?: Prisma.StringFilter<"ResearchJob"> | string
  articlesFound?: Prisma.IntFilter<"ResearchJob"> | number
  articlesProcessed?: Prisma.IntFilter<"ResearchJob"> | number
  startTime?: Prisma.DateTimeNullableFilter<"ResearchJob"> | Date | string | null
  endTime?: Prisma.DateTimeNullableFilter<"ResearchJob"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"ResearchJob"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ResearchJob"> | Date | string
  includedIds?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  excludedIds?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  exclusionReasons?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  reviewText?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
  graphId?: Prisma.StringNullableFilter<"ResearchJob"> | string | null
}

export type ResearchJobCreateManyGraphInput = {
  id: string
  topic: string
  mode: string
  status: string
  progress: number
  error?: string | null
  queries: string
  articlesFound: number
  articlesProcessed: number
  startTime?: Date | string | null
  endTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  includedIds?: string | null
  excludedIds?: string | null
  exclusionReasons?: string | null
  reviewText?: string | null
}

export type ResearchJobUpdateWithoutGraphInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articles?: Prisma.ArticleUpdateManyWithoutJobNestedInput
}

export type ResearchJobUncheckedUpdateWithoutGraphInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  articles?: Prisma.ArticleUncheckedUpdateManyWithoutJobNestedInput
}

export type ResearchJobUncheckedUpdateManyWithoutGraphInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  topic?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  queries?: Prisma.StringFieldUpdateOperationsInput | string
  articlesFound?: Prisma.IntFieldUpdateOperationsInput | number
  articlesProcessed?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  includedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  excludedIds?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  exclusionReasons?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reviewText?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ResearchJobCountOutputType
 */

export type ResearchJobCountOutputType = {
  articles: number
}

export type ResearchJobCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  articles?: boolean | ResearchJobCountOutputTypeCountArticlesArgs
}

/**
 * ResearchJobCountOutputType without action
 */
export type ResearchJobCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJobCountOutputType
   */
  select?: Prisma.ResearchJobCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ResearchJobCountOutputType without action
 */
export type ResearchJobCountOutputTypeCountArticlesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArticleWhereInput
}


export type ResearchJobSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topic?: boolean
  mode?: boolean
  status?: boolean
  progress?: boolean
  error?: boolean
  queries?: boolean
  articlesFound?: boolean
  articlesProcessed?: boolean
  startTime?: boolean
  endTime?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  includedIds?: boolean
  excludedIds?: boolean
  exclusionReasons?: boolean
  reviewText?: boolean
  graphId?: boolean
  articles?: boolean | Prisma.ResearchJob$articlesArgs<ExtArgs>
  graph?: boolean | Prisma.ResearchJob$graphArgs<ExtArgs>
  _count?: boolean | Prisma.ResearchJobCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["researchJob"]>

export type ResearchJobSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topic?: boolean
  mode?: boolean
  status?: boolean
  progress?: boolean
  error?: boolean
  queries?: boolean
  articlesFound?: boolean
  articlesProcessed?: boolean
  startTime?: boolean
  endTime?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  includedIds?: boolean
  excludedIds?: boolean
  exclusionReasons?: boolean
  reviewText?: boolean
  graphId?: boolean
  graph?: boolean | Prisma.ResearchJob$graphArgs<ExtArgs>
}, ExtArgs["result"]["researchJob"]>

export type ResearchJobSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  topic?: boolean
  mode?: boolean
  status?: boolean
  progress?: boolean
  error?: boolean
  queries?: boolean
  articlesFound?: boolean
  articlesProcessed?: boolean
  startTime?: boolean
  endTime?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  includedIds?: boolean
  excludedIds?: boolean
  exclusionReasons?: boolean
  reviewText?: boolean
  graphId?: boolean
  graph?: boolean | Prisma.ResearchJob$graphArgs<ExtArgs>
}, ExtArgs["result"]["researchJob"]>

export type ResearchJobSelectScalar = {
  id?: boolean
  topic?: boolean
  mode?: boolean
  status?: boolean
  progress?: boolean
  error?: boolean
  queries?: boolean
  articlesFound?: boolean
  articlesProcessed?: boolean
  startTime?: boolean
  endTime?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  includedIds?: boolean
  excludedIds?: boolean
  exclusionReasons?: boolean
  reviewText?: boolean
  graphId?: boolean
}

export type ResearchJobOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "topic" | "mode" | "status" | "progress" | "error" | "queries" | "articlesFound" | "articlesProcessed" | "startTime" | "endTime" | "createdAt" | "updatedAt" | "includedIds" | "excludedIds" | "exclusionReasons" | "reviewText" | "graphId", ExtArgs["result"]["researchJob"]>
export type ResearchJobInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  articles?: boolean | Prisma.ResearchJob$articlesArgs<ExtArgs>
  graph?: boolean | Prisma.ResearchJob$graphArgs<ExtArgs>
  _count?: boolean | Prisma.ResearchJobCountOutputTypeDefaultArgs<ExtArgs>
}
export type ResearchJobIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  graph?: boolean | Prisma.ResearchJob$graphArgs<ExtArgs>
}
export type ResearchJobIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  graph?: boolean | Prisma.ResearchJob$graphArgs<ExtArgs>
}

export type $ResearchJobPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ResearchJob"
  objects: {
    articles: Prisma.$ArticlePayload<ExtArgs>[]
    graph: Prisma.$GraphPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    topic: string
    mode: string
    status: string
    progress: number
    error: string | null
    queries: string
    articlesFound: number
    articlesProcessed: number
    startTime: Date | null
    endTime: Date | null
    createdAt: Date
    updatedAt: Date
    includedIds: string | null
    excludedIds: string | null
    exclusionReasons: string | null
    reviewText: string | null
    graphId: string | null
  }, ExtArgs["result"]["researchJob"]>
  composites: {}
}

export type ResearchJobGetPayload<S extends boolean | null | undefined | ResearchJobDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload, S>

export type ResearchJobCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ResearchJobFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ResearchJobCountAggregateInputType | true
  }

export interface ResearchJobDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ResearchJob'], meta: { name: 'ResearchJob' } }
  /**
   * Find zero or one ResearchJob that matches the filter.
   * @param {ResearchJobFindUniqueArgs} args - Arguments to find a ResearchJob
   * @example
   * // Get one ResearchJob
   * const researchJob = await prisma.researchJob.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ResearchJobFindUniqueArgs>(args: Prisma.SelectSubset<T, ResearchJobFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ResearchJob that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ResearchJobFindUniqueOrThrowArgs} args - Arguments to find a ResearchJob
   * @example
   * // Get one ResearchJob
   * const researchJob = await prisma.researchJob.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ResearchJobFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ResearchJobFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ResearchJob that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobFindFirstArgs} args - Arguments to find a ResearchJob
   * @example
   * // Get one ResearchJob
   * const researchJob = await prisma.researchJob.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ResearchJobFindFirstArgs>(args?: Prisma.SelectSubset<T, ResearchJobFindFirstArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ResearchJob that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobFindFirstOrThrowArgs} args - Arguments to find a ResearchJob
   * @example
   * // Get one ResearchJob
   * const researchJob = await prisma.researchJob.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ResearchJobFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ResearchJobFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ResearchJobs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ResearchJobs
   * const researchJobs = await prisma.researchJob.findMany()
   * 
   * // Get first 10 ResearchJobs
   * const researchJobs = await prisma.researchJob.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const researchJobWithIdOnly = await prisma.researchJob.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ResearchJobFindManyArgs>(args?: Prisma.SelectSubset<T, ResearchJobFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ResearchJob.
   * @param {ResearchJobCreateArgs} args - Arguments to create a ResearchJob.
   * @example
   * // Create one ResearchJob
   * const ResearchJob = await prisma.researchJob.create({
   *   data: {
   *     // ... data to create a ResearchJob
   *   }
   * })
   * 
   */
  create<T extends ResearchJobCreateArgs>(args: Prisma.SelectSubset<T, ResearchJobCreateArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ResearchJobs.
   * @param {ResearchJobCreateManyArgs} args - Arguments to create many ResearchJobs.
   * @example
   * // Create many ResearchJobs
   * const researchJob = await prisma.researchJob.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ResearchJobCreateManyArgs>(args?: Prisma.SelectSubset<T, ResearchJobCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ResearchJobs and returns the data saved in the database.
   * @param {ResearchJobCreateManyAndReturnArgs} args - Arguments to create many ResearchJobs.
   * @example
   * // Create many ResearchJobs
   * const researchJob = await prisma.researchJob.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ResearchJobs and only return the `id`
   * const researchJobWithIdOnly = await prisma.researchJob.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ResearchJobCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ResearchJobCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ResearchJob.
   * @param {ResearchJobDeleteArgs} args - Arguments to delete one ResearchJob.
   * @example
   * // Delete one ResearchJob
   * const ResearchJob = await prisma.researchJob.delete({
   *   where: {
   *     // ... filter to delete one ResearchJob
   *   }
   * })
   * 
   */
  delete<T extends ResearchJobDeleteArgs>(args: Prisma.SelectSubset<T, ResearchJobDeleteArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ResearchJob.
   * @param {ResearchJobUpdateArgs} args - Arguments to update one ResearchJob.
   * @example
   * // Update one ResearchJob
   * const researchJob = await prisma.researchJob.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ResearchJobUpdateArgs>(args: Prisma.SelectSubset<T, ResearchJobUpdateArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ResearchJobs.
   * @param {ResearchJobDeleteManyArgs} args - Arguments to filter ResearchJobs to delete.
   * @example
   * // Delete a few ResearchJobs
   * const { count } = await prisma.researchJob.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ResearchJobDeleteManyArgs>(args?: Prisma.SelectSubset<T, ResearchJobDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ResearchJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ResearchJobs
   * const researchJob = await prisma.researchJob.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ResearchJobUpdateManyArgs>(args: Prisma.SelectSubset<T, ResearchJobUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ResearchJobs and returns the data updated in the database.
   * @param {ResearchJobUpdateManyAndReturnArgs} args - Arguments to update many ResearchJobs.
   * @example
   * // Update many ResearchJobs
   * const researchJob = await prisma.researchJob.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ResearchJobs and only return the `id`
   * const researchJobWithIdOnly = await prisma.researchJob.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ResearchJobUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ResearchJobUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ResearchJob.
   * @param {ResearchJobUpsertArgs} args - Arguments to update or create a ResearchJob.
   * @example
   * // Update or create a ResearchJob
   * const researchJob = await prisma.researchJob.upsert({
   *   create: {
   *     // ... data to create a ResearchJob
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ResearchJob we want to update
   *   }
   * })
   */
  upsert<T extends ResearchJobUpsertArgs>(args: Prisma.SelectSubset<T, ResearchJobUpsertArgs<ExtArgs>>): Prisma.Prisma__ResearchJobClient<runtime.Types.Result.GetResult<Prisma.$ResearchJobPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ResearchJobs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobCountArgs} args - Arguments to filter ResearchJobs to count.
   * @example
   * // Count the number of ResearchJobs
   * const count = await prisma.researchJob.count({
   *   where: {
   *     // ... the filter for the ResearchJobs we want to count
   *   }
   * })
  **/
  count<T extends ResearchJobCountArgs>(
    args?: Prisma.Subset<T, ResearchJobCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ResearchJobCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ResearchJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ResearchJobAggregateArgs>(args: Prisma.Subset<T, ResearchJobAggregateArgs>): Prisma.PrismaPromise<GetResearchJobAggregateType<T>>

  /**
   * Group by ResearchJob.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ResearchJobGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ResearchJobGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ResearchJobGroupByArgs['orderBy'] }
      : { orderBy?: ResearchJobGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ResearchJobGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetResearchJobGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ResearchJob model
 */
readonly fields: ResearchJobFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ResearchJob.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ResearchJobClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  articles<T extends Prisma.ResearchJob$articlesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ResearchJob$articlesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArticlePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  graph<T extends Prisma.ResearchJob$graphArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ResearchJob$graphArgs<ExtArgs>>): Prisma.Prisma__GraphClient<runtime.Types.Result.GetResult<Prisma.$GraphPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ResearchJob model
 */
export interface ResearchJobFieldRefs {
  readonly id: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly topic: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly mode: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly status: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly progress: Prisma.FieldRef<"ResearchJob", 'Int'>
  readonly error: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly queries: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly articlesFound: Prisma.FieldRef<"ResearchJob", 'Int'>
  readonly articlesProcessed: Prisma.FieldRef<"ResearchJob", 'Int'>
  readonly startTime: Prisma.FieldRef<"ResearchJob", 'DateTime'>
  readonly endTime: Prisma.FieldRef<"ResearchJob", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"ResearchJob", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ResearchJob", 'DateTime'>
  readonly includedIds: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly excludedIds: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly exclusionReasons: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly reviewText: Prisma.FieldRef<"ResearchJob", 'String'>
  readonly graphId: Prisma.FieldRef<"ResearchJob", 'String'>
}
    

// Custom InputTypes
/**
 * ResearchJob findUnique
 */
export type ResearchJobFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * Filter, which ResearchJob to fetch.
   */
  where: Prisma.ResearchJobWhereUniqueInput
}

/**
 * ResearchJob findUniqueOrThrow
 */
export type ResearchJobFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * Filter, which ResearchJob to fetch.
   */
  where: Prisma.ResearchJobWhereUniqueInput
}

/**
 * ResearchJob findFirst
 */
export type ResearchJobFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * Filter, which ResearchJob to fetch.
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ResearchJobs to fetch.
   */
  orderBy?: Prisma.ResearchJobOrderByWithRelationInput | Prisma.ResearchJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ResearchJobs.
   */
  cursor?: Prisma.ResearchJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ResearchJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ResearchJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ResearchJobs.
   */
  distinct?: Prisma.ResearchJobScalarFieldEnum | Prisma.ResearchJobScalarFieldEnum[]
}

/**
 * ResearchJob findFirstOrThrow
 */
export type ResearchJobFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * Filter, which ResearchJob to fetch.
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ResearchJobs to fetch.
   */
  orderBy?: Prisma.ResearchJobOrderByWithRelationInput | Prisma.ResearchJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ResearchJobs.
   */
  cursor?: Prisma.ResearchJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ResearchJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ResearchJobs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ResearchJobs.
   */
  distinct?: Prisma.ResearchJobScalarFieldEnum | Prisma.ResearchJobScalarFieldEnum[]
}

/**
 * ResearchJob findMany
 */
export type ResearchJobFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * Filter, which ResearchJobs to fetch.
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ResearchJobs to fetch.
   */
  orderBy?: Prisma.ResearchJobOrderByWithRelationInput | Prisma.ResearchJobOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ResearchJobs.
   */
  cursor?: Prisma.ResearchJobWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ResearchJobs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ResearchJobs.
   */
  skip?: number
  distinct?: Prisma.ResearchJobScalarFieldEnum | Prisma.ResearchJobScalarFieldEnum[]
}

/**
 * ResearchJob create
 */
export type ResearchJobCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * The data needed to create a ResearchJob.
   */
  data: Prisma.XOR<Prisma.ResearchJobCreateInput, Prisma.ResearchJobUncheckedCreateInput>
}

/**
 * ResearchJob createMany
 */
export type ResearchJobCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ResearchJobs.
   */
  data: Prisma.ResearchJobCreateManyInput | Prisma.ResearchJobCreateManyInput[]
}

/**
 * ResearchJob createManyAndReturn
 */
export type ResearchJobCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * The data used to create many ResearchJobs.
   */
  data: Prisma.ResearchJobCreateManyInput | Prisma.ResearchJobCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ResearchJob update
 */
export type ResearchJobUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * The data needed to update a ResearchJob.
   */
  data: Prisma.XOR<Prisma.ResearchJobUpdateInput, Prisma.ResearchJobUncheckedUpdateInput>
  /**
   * Choose, which ResearchJob to update.
   */
  where: Prisma.ResearchJobWhereUniqueInput
}

/**
 * ResearchJob updateMany
 */
export type ResearchJobUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ResearchJobs.
   */
  data: Prisma.XOR<Prisma.ResearchJobUpdateManyMutationInput, Prisma.ResearchJobUncheckedUpdateManyInput>
  /**
   * Filter which ResearchJobs to update
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * Limit how many ResearchJobs to update.
   */
  limit?: number
}

/**
 * ResearchJob updateManyAndReturn
 */
export type ResearchJobUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * The data used to update ResearchJobs.
   */
  data: Prisma.XOR<Prisma.ResearchJobUpdateManyMutationInput, Prisma.ResearchJobUncheckedUpdateManyInput>
  /**
   * Filter which ResearchJobs to update
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * Limit how many ResearchJobs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ResearchJob upsert
 */
export type ResearchJobUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * The filter to search for the ResearchJob to update in case it exists.
   */
  where: Prisma.ResearchJobWhereUniqueInput
  /**
   * In case the ResearchJob found by the `where` argument doesn't exist, create a new ResearchJob with this data.
   */
  create: Prisma.XOR<Prisma.ResearchJobCreateInput, Prisma.ResearchJobUncheckedCreateInput>
  /**
   * In case the ResearchJob was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ResearchJobUpdateInput, Prisma.ResearchJobUncheckedUpdateInput>
}

/**
 * ResearchJob delete
 */
export type ResearchJobDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
  /**
   * Filter which ResearchJob to delete.
   */
  where: Prisma.ResearchJobWhereUniqueInput
}

/**
 * ResearchJob deleteMany
 */
export type ResearchJobDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ResearchJobs to delete
   */
  where?: Prisma.ResearchJobWhereInput
  /**
   * Limit how many ResearchJobs to delete.
   */
  limit?: number
}

/**
 * ResearchJob.articles
 */
export type ResearchJob$articlesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Article
   */
  select?: Prisma.ArticleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Article
   */
  omit?: Prisma.ArticleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArticleInclude<ExtArgs> | null
  where?: Prisma.ArticleWhereInput
  orderBy?: Prisma.ArticleOrderByWithRelationInput | Prisma.ArticleOrderByWithRelationInput[]
  cursor?: Prisma.ArticleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ArticleScalarFieldEnum | Prisma.ArticleScalarFieldEnum[]
}

/**
 * ResearchJob.graph
 */
export type ResearchJob$graphArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Graph
   */
  select?: Prisma.GraphSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Graph
   */
  omit?: Prisma.GraphOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GraphInclude<ExtArgs> | null
  where?: Prisma.GraphWhereInput
}

/**
 * ResearchJob without action
 */
export type ResearchJobDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ResearchJob
   */
  select?: Prisma.ResearchJobSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ResearchJob
   */
  omit?: Prisma.ResearchJobOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ResearchJobInclude<ExtArgs> | null
}
