import { databaseManager } from '../src/core/Database';
import { v4 as uuidv4 } from 'uuid';

async function seed() {
    console.log('Seeding large graph...');
    await databaseManager.initialize();

    const graphId = 'large-graph-500';
    const userId = 'stress-user'; // Same as backend stress test

    // Create User if not exists
    const prisma = databaseManager.getClient();
    const user = await prisma.user.upsert({
        where: { id: userId },
        update: {},
        create: {
            id: userId,
            username: 'stress_user',
            email: 'stress@example.com',
            passwordHash: 'hash',
            role: 'user',
            permissions: '[]'
        }
    });

    // Generate 500 nodes
    const nodes = [];
    for (let i = 0; i < 500; i++) {
        nodes.push({
            id: `n${i}`,
            label: `Node ${i}`,
            group: i % 5 === 0 ? 'Cluster A' : 'Cluster B',
            data: { weight: Math.random() }
        });
    }

    // Generate 1000 edges randomly
    const edges = [];
    for (let i = 0; i < 1000; i++) {
        const source = `n${Math.floor(Math.random() * 500)}`;
        const target = `n${Math.floor(Math.random() * 500)}`;
        if (source !== target) {
            edges.push({
                id: `e${i}`,
                source,
                target,
                relation: 'RELATED_TO',
                data: { weight: Math.random() }
            });
        }
    }

    // Delete existing if any
    try {
        await prisma.graph.delete({ where: { id: graphId } });
    } catch (e) { }

    // Create Graph
    await prisma.graph.create({
        data: {
            id: graphId,
            userId,
            name: 'Stress Test Graph (500 Nodes)',
            description: 'generated by seedLargeGraph.ts',
            nodes: JSON.stringify(nodes),
            edges: JSON.stringify(edges),
            version: '2.0',
            directed: true,
            createdAt: new Date(),
            updatedAt: new Date(),
            detailedNodes: {
                create: nodes.map(n => ({
                    label: n.label,
                    name: n.id,
                    data: JSON.stringify(n.data)
                }))
            },
            detailedEdges: {
                create: edges.map(e => ({
                    source: e.source,
                    target: e.target,
                    relation: e.relation,
                    data: JSON.stringify(e.data)
                }))
            }
        }
    });

    console.log('Seeded large graph:', graphId);
    console.log(`Nodes: ${nodes.length}, Edges: ${edges.length}`);
}

seed().catch(console.error);
